### PR TITLE
more options

### PR DESCRIPTION
**Pull request by DanieleMancini**
- added optional parameter includeData to getFingerprint: 
- added more options for: retries, timeout and permissions_to_check
- removed await for getComponentPromises in getFingerprintData

### CODE REVIEW

**Comment by ilkkapeltola** [comment]
I'll check this when I'm back from vacation.
Thanks for the PR 😎

**Comment by DanieleMancini** [comment]
i also added UNMASKED_VENDOR_WEBGL and UNMASKED_RENDERER_WEBGL to hardware,
if you want i can add them in this pr.

**Comment by ilkkapeltola** [comment]
> i also added UNMASKED_VENDOR_WEBGL and UNMASKED_RENDERER_WEBGL to hardware,
> if you want i can add them in this pr.

Yeah please do. Thanks!

**Comment by DanieleMancini** [comment]
done!

**Comment by ilkkapeltola** [comment]
I'm checking this over the weekend.

**Comment by ilkkapeltola** [comment]
@DanieleMancini this is merged, looks good.
Though, I might need to do some adjustments eventually to the options as they are growing, to make them make sense.
What I will do though is I won't do breaking changes before I publish v1.0.0, and keep supporting these ones, but I will likely add the more verbose ones as aliases. For example "retries" is a bit too ambiguous.

**Comment by ilkkapeltola** [comment]
Still need to publish to NPM after my integration tests.

**Pull request merged**
